<?php

namespace WF3\WRTBundle\Repository;

/**
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCartesWithCoordonnees(){
        $qb = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.carte', 'coor')
            ->addSelect('coor')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
